#!/usr/bin/env python3
import os

"""Genera encrypted_strings.h para la edición pública.

El header contiene únicamente bytes XOR con la clave nativa.
El texto claro vive en esta herramienta de compilación y nunca se empaqueta en el APK.
"""

XOR_KEY = bytes((0x7B, 0xE2, 0x4D, 0x93, 0x18, 0x6A, 0xC5, 0x3F))
FREEZY_SECRET_KEY = os.environ.get("FREEZY_SECRET_KEY", "L9RJPV6lBI0IGILcTQO2N2/uGcSnrKgF9vg1BquRyd4=")

STRINGS = {
    1: "https://licenciasfreezy.vercel.app/api/keys/verify",
    2: FREEZY_SECRET_KEY,
    3: "FreezyPrefs",
    4: "freezy_public_prefs_key",
    5: "xRUwi70J41GFIbtkDY38VXIAoWtbsGGG+LWfenCZh7k=,yDu9og255NN5GEf+Bwa9rTrqFQ0EydZ0r1FCh9TdAW4=,hxqRlPTu1bMS/0DITB1SSu0vd4u/8l8TjPgfaAp63Gc=,ft9JFh9fyiSD0LI4vCAyVHDM1OKStfDBooxsWHHvngY=",
    6: "https://whatsapp.com/channel/0029Vb9K5FJ545usgyohs136",
    7: "https://www.tiktok.com/@freezyt",
    8: "Si bien esta herramienta no altera los archivos originales del juego, su uso es bajo tu responsabilidad. La aplicación vincula cada licencia a un HWID persistente del dispositivo para evitar que se comparta entre varios equipos. Lee y acepta este aviso antes de continuar.",
    9: "76A8003C6D98EDB403D651B27612031605F4C5EE4AEF131F6FC230DA7E48CB66",
    10: "FREEZY",
    11: "Inicia sesión con tu licencia oficial",
    12: "USUARIO",
    13: "Ingresa tu usuario",
    14: "LICENCIA",
    15: "Pega tu licencia aquí",
    16: "INGRESAR",
    17: "OBTENER LICENCIA GRATIS",
    18: "Canales oficiales",
    19: "VERIFICACIÓN SEGURA",
    20: "Validando licencia",
    21: "Comprobando tu acceso con el servidor de Freezy",
    22: "VOLVER AL LOGIN",
    23: "AVISO IMPORTANTE",
    24: "DESCARGO DE RESPONSABILIDAD",
    25: "Lee cuidadosamente antes de continuar",
    26: "ACEPTO Y CONTINÚO",
    27: "NO ACEPTO · SALIR",
    28: "ACTUALIZACIÓN REQUERIDA",
    29: "Hay una nueva versión disponible",
    30: "Actualiza para continuar usando Freezy",
    31: "ABRIR WHATSAPP",
    32: "Novedades en TikTok",
    33: "Cambios, avisos y demostraciones",
    34: "ACCESO AUTORIZADO",
    35: "Licencia válida",
    36: "Identidad y licencia verificadas correctamente",
    37: "ACCESO VENCIDO",
    38: "Licencia expirada",
    39: "Renueva tu licencia para continuar",
    40: "CONEXIÓN INTERRUMPIDA",
    41: "Error de red",
    42: "Comprueba tu conexión e inténtalo nuevamente",
    43: "SERVICIO PAUSADO",
    44: "Servidor en mantenimiento",
    45: "Estamos realizando mejoras. Inténtalo más tarde",
    46: "ACCESO DENEGADO",
    47: "Licencia no válida",
    48: "Revisa los datos e inténtalo nuevamente",
    49: "Canal de WhatsApp",
    50: "TikTok",
    51: "su",
    52: "exit\n",
    53: "iptables -D INPUT -p udp --sport 7000:25000 -j FREEZY_FAKELAG 2>/dev/null",
    54: "iptables -F FREEZY_FAKELAG 2>/dev/null",
    55: "iptables -X FREEZY_FAKELAG 2>/dev/null",
    56: "iptables -N FREEZY_FAKELAG",
    57: "iptables -I INPUT -p udp --sport 7000:25000 -j FREEZY_FAKELAG",
    58: "iptables -A FREEZY_FAKELAG -j DROP",
    59: "com.dts.freefiremax",
    60: "com.dts.freefireth"
}


def encrypt(value: str) -> list[int]:
    raw = value.encode("utf-8")
    return [byte ^ XOR_KEY[index % len(XOR_KEY)] for index, byte in enumerate(raw)]


def main() -> None:
    print("// Generated by encrypt_strings.py. Do not edit manually.")
    print("#pragma once")
    print("#include <cstddef>")
    print("#include <cstdint>")
    print("namespace encrypted_strings {")
    print("static constexpr uint8_t KEY[] = {" + ", ".join(f"0x{x:02X}" for x in XOR_KEY) + "};")
    for string_id, value in STRINGS.items():
        encoded = encrypt(value)
        print(f"static constexpr uint8_t S{string_id}[] = {{" + ", ".join(f"0x{x:02X}" for x in encoded) + "};")
    print("struct Entry { int id; const uint8_t* data; size_t size; };")
    print("static constexpr Entry ENTRIES[] = {")
    for string_id in STRINGS:
        print(f"    {{{string_id}, S{string_id}, sizeof(S{string_id})}},")
    print("};")
    print("}")


if __name__ == "__main__":
    main()
